# Use the official Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY script.py .

# Set the default command to run the script
ENTRYPOINT ["python", "script.py"]

#docker run python-runtime-args-example arg1 arg2arg3 abc3
